# -*- coding: utf-8 -*-
"""
해달아카이브(Google Sheets/Apps Script) → shinhaedal.art 데이터 동기화
- 공개 화이트리스트 필드만 추출 (민감정보: 실거래가/소장자/결제/판매경로 등은 절대 내보내지 않음)
- 데이터 검증 실패 시 exit 1 → 기존 파일 유지 (사이트는 마지막 정상본으로 계속 운영)
"""
import json, os, sys, urllib.request, urllib.parse, datetime

API = os.environ.get("ARCHIVE_API", "").strip()
if not API:
    sys.exit("ARCHIVE_API_URL secret이 설정되지 않았습니다.")

# ── 공개 필드 화이트리스트 ─────────────────────────────
PUBLIC_WORK_FIELDS = ["no", "image", "title", "caption", "material", "size", "year", "sold", "exhibitions"]
INCLUDE_PRICE = False   # 판매가격 공개하려면 True 로 변경
if INCLUDE_PRICE:
    PUBLIC_WORK_FIELDS.append("price")

EXHIBITION_FIELDS = ["id", "title", "venue", "start_date", "end_date", "work_nos", "docent_url", "type", "note_public"]

OUT_DIR = "data"

def fetch(sheet=None):
    url = API + ("?" + urllib.parse.urlencode({"sheet": sheet}) if sheet else "")
    req = urllib.request.Request(url, headers={"User-Agent": "haedal-sync-bot"})
    with urllib.request.urlopen(req, timeout=60) as r:
        raw = r.read().decode("utf-8")
    data = json.loads(raw)
    # {rows:[...]} / {data:[...]} / [...] 모두 허용
    if isinstance(data, dict):
        data = data.get("rows") or data.get("data") or []
    if not isinstance(data, list):
        raise ValueError("Unexpected response shape")
    return data

def pick(row, fields):
    return {k: str(row.get(k, "") or "").strip() for k in fields}

def validate_works(rows):
    if len(rows) == 0:
        raise ValueError("작품 데이터가 0건 — 반영 중단")
    missing = [r for r in rows if not r["no"] or not r["title"]]
    if len(missing) > len(rows) * 0.3:
        raise ValueError(f"작품번호/작품명 누락이 {len(missing)}건 — 시트 구조 변경 의심, 반영 중단")
    # 이전 반영본 대비 급감 감지 (실수로 대량 삭제된 경우 보호)
    prev_path = os.path.join(OUT_DIR, "works.js")
    if os.path.exists(prev_path):
        try:
            prev_txt = open(prev_path, encoding="utf-8").read()
            prev_cnt = prev_txt.count('"no"')
            if prev_cnt >= 4 and len(rows) < prev_cnt * 0.5:
                raise ValueError(f"작품 수 급감({prev_cnt}→{len(rows)}) — 반영 중단, 의도한 삭제라면 수동 실행으로 확인")
        except ValueError:
            raise
        except Exception:
            pass

def write_js(path, varname, payload):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// auto-generated by sync_data.py — {stamp}\n// 직접 수정 금지: 해달아카이브에서 수정하세요\nconst {varname} = {body};\n")

def main():
    works_raw = fetch()  # 기본 = 작품 시트
    works = [pick(r, PUBLIC_WORK_FIELDS) for r in works_raw]
    validate_works(works)
    write_js(os.path.join(OUT_DIR, "works.js"), "WORKS", works)
    print(f"works.js: {len(works)}건")

    try:
        ex_raw = fetch("exhibitions")
        exhibitions = [pick(r, EXHIBITION_FIELDS) for r in ex_raw if str(r.get("title", "")).strip()]
    except Exception as e:
        print(f"전시 시트 읽기 실패({e}) — 전시 없음으로 처리")
        exhibitions = []
    write_js(os.path.join(OUT_DIR, "exhibitions.js"), "EXHIBITIONS", exhibitions)
    print(f"exhibitions.js: {len(exhibitions)}건")

if __name__ == "__main__":
    main()
